name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Commit e Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando animação Snake"
          branch: output
          file_pattern: "dist/snake.svg"
